ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 12

[[structure]]
name = "flare"
file = "images/Flare.png"
startx = 1365
starty = 869

#[[structure]]
#name = "lazulight"
#file = "images/Lazulight.png"
#startx = 1884
#starty = 733

[[structure]]
name = "suisei"
file = "images/suisei.png"
startx = 1451
starty = 1076

[[structure]]
name = "niji_main"
file = "images/Nijisanji logo.png"
startx = 165
starty = 721

#[[structure]]
#name = "vshojo"
#file = "images/vshojo.png"
#startx = 163
#starty = 747

#[[structure]]
#name = "sanbaka + others"
#file = "images/Sanbaka + Others.png"
#startx = 240
#starty = 737

[[structure]]
name = "yagoo"
file = "images/Yagoo3.png"
startx = 1332
starty = 900

[[structure]]
name = "main area"
file = "images/logo area.png"
startx = 200
starty = 720

[[structure]]
name = "holostars"
file= "images/holostars.png"
startx = 303
starty = 759

[[structure]]
name = "fubuhappy"
file = "images/fubuhappy.png"
startx = 1333
starty = 870

[[structure]]
name = "shuba"
file = "images/shuba area(w yagoo).png"
startx = 230
starty = 782

[[structure]]
name = "all_fubu_stuff"
file = "images/all_fubu_stuff.png"
startx = 1332
starty = 1042

[[structure]]
name = "more-vshojo"
file = "images/more-vshojo.png"
startx = 1333
starty = 1168