ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 12

[[structure]]
name = "flare"
file = "images/Flare.png"
startx = 1365
starty = 869

#[[structure]]
#name = "lazulight"
#file = "images/Lazulight.png"
#startx = 1884
#starty = 733

[[structure]]
name = "ChibiWall"
file = "images/ChibiWall.png"
startx = 1454
starty = 1063

[[structure]]
name = "suisei"
file = "images/suisei.png"
startx = 1450
starty = 1074

[[structure]]
name = "niji_main"
file = "images/Nijisanji logo.png"
startx = 165
starty = 721

#[[structure]]
#name = "vshojo"
#file = "images/vshojo.png"
#startx = 163
#starty = 747

#[[structure]]
#name = "sanbaka + others"
#file = "images/Sanbaka + Others.png"
#startx = 240
#starty = 737

[[structure]]
name = "yagoo"
file = "images/Yagoo3.png"
startx = 1332
starty = 900

[[structure]]
name = "main area"
file = "images/logo area.png"
startx = 200
starty = 720

[[structure]]
name = "holostars"
file= "images/holostars.png"
startx = 302
starty = 758

[[structure]]
name = "fubuhappy"
file = "images/FubuHappy.png"
startx = 1333
starty = 870

[[structure]]
name = "shuba"
file = "images/shuba area(w yagoo).png"
startx = 230
starty = 782

[[structure]]
name = "Rushia"
file = "images/rushia.png"
startx = 1397
starty = 1067

[[structure]]
name = "all_fubu_stuff"
file = "images/all_fubu_stuff.png"
startx = 1332
starty = 1042

[[structure]]
name = "matsuribibi"
file = "images/matsuri.png"
startx = 1423
starty = 1068

[[structure]]
name = "more-vshojo"
file = "images/more-vshojo.png"
startx = 1415
starty = 1168

[[structure]]
name = "pixelpeko"
file = "images/pixelpeko.png"
startx = 1363
starty = 986

[[structure]]
name = "olaaaa"
file = "images/Olaaaa.png"
startx = 1332
starty = 1172

[[structure]]
name = "Watamelon"
file = "images/Watame_final.png"
startx = 1391
starty = 1086

[[structure]]
name = "kaf_final"
file = "images/kaf_final.png"
startx = 1419
starty = 1104

[[structure]]
name = "starticon.png"
file = "images/starticon.png"
startx = 1028
starty = 1971

[[structure]]
name = "Niji South"
file = "images/NijiSouth.png"
startx = 1501
starty = 1064




# Add everything above this!!!
[[structure]]
name = "template_fixes.png"
file = "images/template_fixes.png"
startx = 0
starty = 0
