ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 11

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "rplacede_schriftzug"
file = "images/rplacede_schriftzug.png"
startx = 0
starty = 856
priority = 3

[[structure]]
name = "maus"
file = "images/maus.png"
startx = 58
starty = 832
priority = 2

[[structure]]
name = "adler"
file = "images/adler.png"
startx = 254
starty = 830
priority = 2

[[structure]]
name = "brot"
file = "images/brot.png"
startx = 169
starty = 830
priority = 2
#
# [[structure]]
# name = "saeule"
# file = "images/saeule.png"
# startx = 431
# starty = 829
# priority = 0

[[structure]]
name = "eu-taube"
file = "images/eu-taube.png"
startx = 388
starty = 833
priority = 2

[[structure]]
name = "autobahn"
file = "images/autobahn.png"
startx = 539
starty = 838
priority = 2

[[structure]]
name = "ice"
file = "images/ice.png"
startx = 326
starty = 849
priority = 2
