ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
	[0xff, 0x00, 0xf8, 0xff]
]

version = 13

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "logo"
file = "images/everything.png"
startx = 1333
starty = 753
priority = 3

[[structure]]
name = "fish-background"
file = "images/fish-background.png"
startx = 1333
starty = 753
priority = 2

[[structure]]
name = "augsburg"
file = "images/augsburg.png"
startx = 1333
starty = 753
priority = 3
