name: Generate and push

on:
  workflow_dispatch:

  push:
    paths:
      - 'scripts/generate_json.py'
      - 'scripts/render_json.py' 
      - 'images/**'
      - 'config.toml'

permissions:
  contents: write

jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    container:
      image: python:3
    steps:    
      - uses: actions/checkout@v3

      - run: |
          pip3 install -r scripts/requirements.txt
        
      - name: Generate json
        run: python scripts/generate_json.py
        shell: sh

      - name: Generate Pixelart
        run: python scripts/render_json.py
        shell: sh

      - uses: EndBug/add-and-commit@v7
        with:
          message: "Add generated pixel.json [Generate]"
